version: '2'
services:
  db:
    image: postgres
  web:
    image: 'noamt/djanga:master'
    command: "bash -c \"echo \\\"Waiting for DB\\\"; while ! nc -z db 5432; do sleep 0.1; done; python manage.py runserver 0.0.0.0:8000\""
    ports:
      - 8000
    links:
      - db
